name = "nightstudy"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "nightstudy"
database_id = "YOUR_D1_DATABASE_ID"

[triggers]
crons = ["0 15 * * 1-5"]

[vars]
CHECKIN_DEADLINE = "18:00:00"
GOOGLE_SPREADSHEET_ID = "15rlBMtj7DIGguoJcRmFY3piZBr7uU4mAU51BRQHSwUo"
